# Generated by Django 4.0.5 on 2022-06-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_contact_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='agenda/img/%Y/%m/%d'),
        ),
    ]
