# Generated by Django 4.0.5 on 2022-06-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_contact_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='to_show',
            field=models.BooleanField(default=True),
        ),
    ]
