# Generated by Django 4.0.5 on 2022-06-22 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_contact_to_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.category'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
